### ISSUE TITLE
Fix the back button for approve mentor page

### ISSUE THREAD

**Issue by TheSlimyOne** [adamuremek/mentorship-program#75]
Clicking the back arrow to the admin dashboard from approve mentor button errors out.

Route /view_pending
The back arrow called Administator Dashboard

**Comment by mdloucks** [comment]
On it 🫡

**Comment by mdloucks** [comment]
Good catch! I believe you're seeing that error because you're not logged in. The /view_pending route currently doesn't require any auth to view which should probably be changed.

![Screenshot 2024-03-20 at 12 11 32 PM](https://github.com/adamuremek/mentorship-program/assets/19471665/e6660005-9b4c-4844-a730-24f195701607)

When not logged in:

![Screenshot 2024-03-20 at 12 11 48 PM](https://github.com/adamuremek/mentorship-program/assets/19471665/c7beae0a-a55f-4e08-9f9d-b40631f6cedd)
